### ISSUE TITLE
License (is there possibility of reuse?)

### ISSUE THREAD

**Issue by jlacko** [garrettgman/rmarkdown-the-bigger-picture#2]
I really like the Gosset & his manager communication exchange and would like to reuse a part of it in my training (with attribution).
However the repo has no license file, and no indication whether CC-BY or CC-BY-SA is possible.
Could you please provide a license?

**Comment by garrettgman** [comment]
No problem. Enjoy!

**Comment by jlacko** [comment]
Thank you very much @garrettgman, I feel very legal now :)
